alter table receipts drop constraint if exists receipts_status_check;
alter table receipts add constraint receipts_status_check check (status in ('processing','needs_review','approved','rejected','inbox'));
alter table receipts alter column status set default 'processing';
alter table receipts add column if not exists confidence_score numeric;

create table if not exists research_runs (
  id text primary key,
  created_at timestamp default now(),
  receipt_count integer not null,
  month text not null,
  notes text
);

create table if not exists research_metrics (
  id bigint generated by default as identity primary key,
  run_id text references research_runs(id) on delete cascade,
  metric_key text not null,
  metric_value numeric not null
);
