-- Users (single-row MVP)
create table if not exists users (
  id text primary key,
  email text,
  created_at timestamp default now()
);

create table if not exists policies (
  user_id text primary key references users(id),
  per_diem numeric default 60.00,
  receipt_required_over numeric default 25.00,
  restricted_categories text default '[]'
);

create table if not exists receipts (
  id text primary key,
  user_id text references users(id),
  created_at timestamp default now(),
  status text check (status in ('inbox','approved','rejected')) default 'inbox',
  file_path text not null,
  ocr_text text,
  date date,
  vendor text,
  amount numeric,
  tax numeric,
  currency text default 'USD',
  category text,
  payment_method text,
  memo text,
  policy_flags jsonb default '[]',
  duplicate_of text
);

create table if not exists logs (
  id bigint generated by default as identity primary key,
  receipt_id text references receipts(id),
  step text,
  message text,
  ts timestamp default now()
);

create or replace function set_default_user()
returns trigger as $$
begin
  if not exists(select 1 from users) then
    insert into users(id, email) values('usr_seed', 'owner@example.com') on conflict do nothing;
    insert into policies(user_id) values('usr_seed') on conflict do nothing;
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger ensure_user before insert on receipts
for each row execute function set_default_user();
